### PR TITLE
feat: add option of padding in sidebar

### PR DESCRIPTION
**Pull request by jaeheonji**
Hi! First of all, I'm so happy and excited to know this awesome plugin.

I like `cokeline` sidebar feature. but, one thing, I wish there was an option to further customize the UI.

For example:
화면 캡처 2022-04-04 213200

It would be nice if we could adjust the length of the entire width of the component like this.
화면 캡처 2022-04-04 213140

So I simply added a padding option. Please let me know if there is anything I missed or need to be corrected 😸

### CODE REVIEW

**Comment by jaeheonji** [comment]
Thanks for the reply!

> Correct me if I'm wrong, but that option would only be useful when setting padding = 1, correct?

probably, in most cases, you are right.

> Btw, the reason nvim-cokeline seems to be off by one column is that it only considers the width of the sidebar, ignoring the column used to display the vertical split. I think a better option in this case is to just link VertSplit to Normal.

Yes. that could be one way. but, I think it's better to have padding if the user customizes the theme by considering the statusline.
So I think that bufferline.nvim may have a [similar option](https://github.com/akinsho/bufferline.nvim#sidebar-offset-1).

**Comment by colin-heffernan** [comment]
Is there any reason this never got merged? This seems like it would be a useful customization option for those who don't want to mess with the way their splits look.

**Comment by jaeheonji** [comment]
I closed this PR as I thought it was unmanaged. If you think we need this, I'll open it again.

**Comment by willothy** [comment]
Is this something people would still want? I'm happy to look into it and possibly merge if so.

**Comment by gingjin** [comment]
@willothy Yes,I need it,thanks:)

**Pull request closed without merging**
